version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=up_trader
      - POSTGRES_PASSWORD=up_trader
      - POSTGRES_DB=up_trader_db


volumes:
  postgres_data: